name: multilayer_simulator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
# Essential
  - numpy
  - attrs>=21.3.0
# Interactive
  - jupyter
  - jupyterlab
  - jedi>=0.17.2 # Enable tab completion
  - ipykernel
# Code formatting
  - black
  - flake8
# Data formats
  # - pandas
  - xarray
# Plotting
  - matplotlib
  - holoviews
# Testing
  - pytest
  - pip
  - pip:
    - -e .